server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Главная страница
    location / {
        try_files $uri $uri/ =404;
    }

    # Redirect example     	
    location = /redirect {
    return 302 /;
   }
    # Раздача изображений
    location /images/ {
        alias /usr/share/nginx/images/;
        autoindex on;
    }

    # Раздача музыки
    location /music/ {
        alias /usr/share/nginx/music/;
        autoindex on;
    }

    # Reverse proxy на backend контейнер
    location /app/ {
      default_type text/plain;
      return 200 "Backend is available only in docker-compose mode\n";
}
}
